### ISSUE TITLE
Unable to link a user to a different organization on CC

### ISSUE THREAD

**Issue by ArseneMwenze** [LULA-LOOP/.github#11]
### Current Behavior

On Command Centre > User management > Users > Edit > Roles … when a user (from the operations team) tries to link a profile (that was already linked to an organization) to a different organization. The dashboard process the changes but does not save them.

### Expected Behavior

On Command Centre > User management > Users > Edit > Roles … when a user from the operations team) tries to link themselves or any other account to an organization. The dashboard must save the changes.

### Steps to Reproduce

1. Log into CC
2. Go to "User Mgt"
3. Go to "Users"
4. Go to a profile that was already linked to an organization 
5. Click on "Edit" on any user profile 
6. Go to "Roles"
7. Link the profile to a different 
8. Go to another page then come back to the same profile 

### Reproduction Link

https://dashboard.lulaloop.co.za/users/220

### What browsers are you seeing the problem on?

Safari

**Comment by thokozanilula** [comment]
@xabiso-nordy @ArseneMwenze I feel like the journey is incomplete with the steps to reproduce. What option was taken before assigning the role? Was it one of the following before attempting to re-link or both?

**Options**
a. Unlink
b. Delete

**Comment by ArseneMwenze** [comment]
The option selected was "unlink"

**Comment by ArseneMwenze** [comment]
Hi team @xabiso-nordy @thelulaloop 
Kindly note thank this issue has been  previously resolved already. Please close ticket.Thank you.

**Comment by xabiso-nordy** [comment]
Noted. Thanks @ArseneMwenze 
I will close the ticket
