### ISSUE TITLE
Unable to see all trips on Command centre - Command centre 

### ISSUE THREAD

**Issue by thelulaloop** [LULA-LOOP/.github#15]
Add a title
Unable to see all trips on Command centre
Current Behaviour 
1. Press on Loop Management
2. Press on Trips
The system automatically puts you on today's trips. The system then buffers and puts out a error saying 'something went wrong.
Additionally when clicking on past trips the system just buffers and the page never loads, same with tomorrows trips and active trips
Expected Behaviour 
I should be able to click on Loop management
Click on trips
then the system should be able to show me a list of all todas trips in sequence from the closest from now till the latest trips.
Steps to Reproduce
Login to command centre
Click on Loop Management
Click on Trips
The system should automatically load all the upcoming trips for today. Whic is not.
When you click on past, Tomorrow and Active trips the system should also be able show you all those trips in sequence.
Reproduction Link
https://dashboard.lulaloop.co.za/trips
Additional Information

What platform is this issue being experienced on?
Command centre
Bug submitted by: @Maps Helepi

**Comment by thelulaloop** [comment]
Hi @ArseneMwenze , please test this, it should be working.

**Comment by ArseneMwenze** [comment]
Hi @thelulaloop 

I can confirm that this issue is no longer occurring.

Thank you.

**Comment by ArseneMwenze** [comment]
Hi team @thelulaloop @xabiso-nordy 
Kindly note this issue is no longer happening.
Thank you
