### ISSUE TITLE
Amp5 organization Audit log - Organisation Dashboard 

### ISSUE THREAD

**Issue by thelulaloop** [LULA-LOOP/.github#19]
Add a title
Amp5 organization Audit log
Current Behaviour 
Currently, the Audit log function is buffering. Al admins are unable to keep track of the changes that are taking place in their organization on a weekly basis
Expected Behaviour 
The Audit log function should display all changes and amendment that took place by Who, when and on which platform.
Steps to Reproduce
I logged into the Amp5 organization dashboard, clicked on audit log function and did a hard refresh but still nothing changed.
Reproduction Link
https://organizations.lulaloop.co.za/audit-logs
Additional Information

What platform is this issue being experienced on?
Organisation Dashboard
Bug submitted by: @Larissa Mawonde

**Comment by ArseneMwenze** [comment]
Hi team, 

Is there perhaps any updates on this ?

Operations and some operators have followed up on the issue, which still appears to be a blocker on their sides.

**Comment by thelulaloop** [comment]
Hi @ArseneMwenze , we will only look into it next sprint

**Comment by ArseneMwenze** [comment]
Noted. Thank you

**Comment by xabiso-nordy** [comment]
Test passed  🚀
