### ISSUE TITLE
"Cancelled" colum on the Cancelled page is inaccurate - Command centre 

### ISSUE THREAD

**Issue by thelulaloop** [LULA-LOOP/.github#27]
Add a title
"Cancelled" colum on the Cancelled page is inaccurate
Current Behaviour 
On Command Centre, Under the "Bookings" page, and "Cancelled" tab, the trips that page are showing "No" on the cancelled column which is confusing for users that it implies they were not cancelled.
Expected Behaviour 
On Command Centre, Under the "Bookings" page, and "Cancelled" tab, the trips that page should be showing "Yes" on the cancelled column to confirm that they were in fact cancelled.
Steps to Reproduce
1. Log into CC
2. Go to "Trips" page
3. Go to "Bookings"
4. Go to "Cancelled" tab
5. Look at the Cancelled column
Reproduction Link
https://dashboard.lulaloop.co.za/bookings
Additional Information

What platform is this issue being experienced on?
Command centre
Bug submitted by: @Arsene Mwenze

**Comment by HoganFortuin2000** [comment]
![Image](https://github.com/user-attachments/assets/d0646186-d12f-4b0b-a5fd-a6680c758b4b)
