### ISSUE TITLE
LUNO Organization Dashboard Unaccessible - Command centre 

### ISSUE THREAD

**Issue by thelulaloop** [LULA-LOOP/.github#28]
Add a title
LUNO Organization Dashboard Unaccessible
Current Behaviour 
When the Administrator she is unable to access any of the functionality on the dashboard when she clicked on any of them.
On Ops Side, unable to have access to LUNO organization dashboard when we tried to link ourselves from Command Centre.
Expected Behaviour 
When the administrator logs in to the dashboard, he/she should have access to any of the functions such as view bookings or loops.
On Ops side, we should be able to link ourselves to LUNO dashboard from command centre .
Steps to Reproduce
1. Login to the organization dashboard
2. Clicked on bookings
3 Observed

AND

1. Login to Command Centre
2. Go to Users
3. Search for Larissa Marlene Mawonde
4. Clicked on role- under Action Clicked on link
5. Select LUNO as account and Admin as role.
6. Observed
Reproduction Link
https://dashboard.lulaloop.co.za/users/54
Additional Information
The LUNO Organization profile is also not displaying under Customers as an Organization from Command Centre.
What platform is this issue being experienced on?
Command centre
Bug submitted by: @Larissa Mawonde

**Comment by ArseneMwenze** [comment]
Hi team @thelulaloop @xabiso-nordy 
Kindly note that this issue was resolved and can be closed.
Thank you.
