### ISSUE TITLE
Trip logs are showing "onboarded" instead of "arrived at" for locations 

### ISSUE THREAD

**Issue by ArseneMwenze** [LULA-LOOP/.github#3]
### Current Behavior

On Command Center, under "Trips" , when a user clicks on a trip's logs, the line of data referring to when the driver arrived at a location is showing "onboarded" and "offloaded" instead of "arrived at" which is confusing clients whenever Operations share trip logs to back up our reports on how specific trips took place.

### Expected Behavior

On Command Center, under "Trips" , when a user clicks on a trip's trip logs, the line of data referring to when the driver arrived at a location should be showing "arrived at" to confirm that the driver did arrive at the pick up but no one has been onboarded on the trip yet.

### Steps to Reproduce

1. Log into Command Center
2. Go to "Loops Mgt" >  "Trips" 
3. Go to "Past trips"
4. Click on "View Trip"
5. Look for lines that say "onboarded" and offloaded" but only have addresses with no commuter names.

### Reproduction Link

https://dashboard.lulaloop.co.za/trips/214240

### What browsers are you seeing the problem on?

Multiple Browsers

### Screenshot (Optional)

![trip logs](https://github.com/LULA-LOOP/.github/assets/173275644/e4d2f13c-21ee-4ea1-a53c-967b1d1ba2c4)

**Comment by ArseneMwenze** [comment]
![Uploading trip logs.png…]()

**Comment by Ediezzle** [comment]
Test evidence:


![Image](https://github.com/user-attachments/assets/d5ea6bcc-32a8-493b-994d-f02e7365f689)
