### ISSUE TITLE
"Total Number Of Trips Per Driver Report" on CC generates inaccurate data - Command centre 

### ISSUE THREAD

**Issue by thelulaloop** [LULA-LOOP/.github#32]
Add a title
"Total Number Of Trips Per Driver Report" on CC generates inaccurate data
Current Behaviour 
On CC, under reports, the "Total Number Of Trips Per Driver Report" displays inaccurate data. 

The report has a mandatory filter per operator. However, regardless of which operator is selected, the reports always displays all drivers.
Expected Behaviour 
On CC, under reports, the "Total Number Of Trips Per Driver Report" must only show the drivers that belong to the operator selected.
Steps to Reproduce
1. Log into CC
2. Go to reports
3. Select Total Number Of Trips Per Driver Report
4. Select an operator 
5. Generate the report
6. Look at the data
Reproduction Link

Additional Information

What platform is this issue being experienced on?
Command centre
Bug submitted by: @Arsene Mwenze

**Comment by xabiso-nordy** [comment]
@evidencefrank please provide evidence 
I tried to test on dev but did not receive the email. I think emails are disabled on dev.

**Comment by xabiso-nordy** [comment]
> [@evidencefrank](https://github.com/evidencefrank) please provide evidence I tried to test on dev but did not receive the email. I think emails are disabled on dev.

Ignore the previous comments. There was delay on emails
Test Passed 🚀
