### ISSUE TITLE
Unable to create individual commuter profiles from Org dashboard - Organisation Dashboard 

### ISSUE THREAD

**Issue by ArseneMwenze** [LULA-LOOP/.github#41]
Add a title
Unable to create individual commuter profiles from Org dashboard
Current Behaviour 
On the organisation dashboard, when a user (admin) tries to create an individual commuter profile, the dashboard generates an error saying "Not allowed, Something went wrong, if the problem persists please contact support". And does not actually saves the profile's details.
Expected Behaviour 
On the organisation dashboard, when a user (admin) tries to create an individual commuter profile, the dashboard must actually save the profile's details.
Steps to Reproduce
1. Log into Org dash
2. Go to "commuters"
3. Click on "Create"
4. Type in all the profiles details
5. Click on "Save"
6. Oserve
Reproduction Link
https://organizations.lulaloop.co.za/commuters/_new
Additional Information
The bug is on production.

The log in details of the org dashboard tested on are :
info+lula@lulaloop.co.za
password
What platform is this issue being experienced on?
Organisation Dashboard
Bug submitted by: @Arsene Mwenze

**Comment by thelulaloop** [comment]
Issue resolved 🚀
