### ISSUE TITLE
CC is duplicating banking details on drivers' profiles

### ISSUE THREAD

**Issue by ArseneMwenze** [LULA-LOOP/.github#7]
### Current Behavior

on CC, under "Drivers" > "Banking details", when a user tries to update a driver's banking details, the Command centre creates another an additional banking profile instead of updating the edited one. And when a user creates new banking details, the CC duplicates the newly created details.

### Expected Behavior

on CC, under "Drivers" > "Banking details", when a user tries to update a driver's banking details, the CC should only update the banking details that are being edited. And when a user creates new banking details, the CC should only create one banking profile (instead of duplicated ones)

### Steps to Reproduce

1. Log into CC
2. Click on drivers
3. Click on Banking details
4. Try to update banking details or create new banking details

### Reproduction Link

https://dashboard.lulaloop.co.za/drivers/49

### What browsers are you seeing the problem on?

Safari

### Screenshot (Optional)

https://github.com/user-attachments/assets/874bc713-c135-40d3-892e-e2f75e3fbc21

### Additional Information

https://github.com/user-attachments/assets/bcdb4474-380a-4591-8f0d-80aef55b2a5d

**Comment by Ediezzle** [comment]
Evidence:


https://github.com/user-attachments/assets/0375ac06-5121-4360-91d3-ec1df2ff82d3

**Comment by ArseneMwenze** [comment]
Hi team @xabiso-nordy @thelulaloop 
Kindly note thank this issue has been  previously resolved already. Please close ticket.Thank you 🙏

**Comment by xabiso-nordy** [comment]
Noted. Thanks @ArseneMwenze 
I will close the task
