### ISSUE TITLE
24h time format on "Trips" page on CC

### ISSUE THREAD

**Issue by ArseneMwenze** [LULA-LOOP/.github#8]
### Feature Description

On CC, Under "Loops management" > "Trips" page, the time format for trips should be 24h. The Command Centre should display "13:00" instead of "01:00pm" etc

### Motivation

As per operations team feedback, this time format is visually better when keeping up with all the trips taking place on a daily basis as it prevents confusion.

### Describe Preferred Solution

On CC, Under "Loops management" > "Trips" page, the time format for trips should be 24h. The Command Centre should display "13:00" instead of "01:00pm" etc

### Design Details

The Command Centre should display "13:00" instead of "01:00pm"
"14:00" instead of "02:00pm"
"15:00" instead of "03:00pm" etc

### Additional Information

![Screenshot 2024-07-19 at 14 59 09](https://github.com/user-attachments/assets/d11a42d1-c3e0-4ca7-804c-ac043da0e27b)

**Comment by xabiso-nordy** [comment]
@ArseneMwenze I'm deleting this feature request because it was done as part of a platform-wide improvement where we changed the time format across the LULA platform to 24 hours instead of 12 hours.
